### ISSUE TITLE
Could we use the Release feature for update.freshrss.org?

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/update.freshrss.org#16]
Follow up from https://github.com/FreshRSS/FreshRSS/issues/6734:

If we would use the Release feature of this (`update.freshrss.org`) Github repository users could track the updates a bit better.

![grafik](https://github.com/user-attachments/assets/df2c7051-4397-4bd7-a113-c7ad7e30ff48)

Who should add the next release there?
@marienfressinaud when he updated `update.freshrss.org`
@Alkarex , @Frenzie , or me after the feedback from @marienfressinaud when the update was done.

What do you think?

**Comment by Alkarex** [comment]
The main idea of https://github.com/FreshRSS/FreshRSS/pull/1760 was indeed to use the GitHub release information and remove the need for manual updates of `update.freshrss.org`.
Note that it is only a problem for ZIP-based installs (which I recommend to avoid if possible) and not for git-based installs or Docker-based installs.

Back to https://github.com/FreshRSS/FreshRSS/issues/6734 for the near future, if we let @marienfressinaud merge the updates on https://github.com/FreshRSS/update.freshrss.org, then users of ZIP-based installs could use the Atom feed https://github.com/FreshRSS/update.freshrss.org/commits/master/.atom

**Comment by Alkarex** [comment]
Related to this comment https://github.com/FreshRSS/update.freshrss.org/pull/13#issuecomment-2156059737

**Comment by marienfressinaud** [comment]
Just to be sure: is there anything expected from me on this ticket? :)

**Comment by Alkarex** [comment]
@marienfressinaud No, except that if you update `update.freshrss.org` immediately when you merge an update PR, then people stuck with a ZIP update mechanism can track https://github.com/FreshRSS/update.freshrss.org/commits/master/.atom to know when there is an update. At least until we revise the update mechanism :-)

**Comment by Alkarex** [comment]
Or use the full *release* mechanism as proposed by @math-GH , which would be a bit better but maybe a bit overkill

**Comment by marienfressinaud** [comment]
I already update `update.freshrss.org` right after merging the PRs, so I think we can stay with the feed of commits ;)
