### ISSUE TITLE
Web update, UPDATE

### ISSUE THREAD

**Issue by howiefc** [FreshRSS/update.freshrss.org#6]
Any chance you can update the version on update.freshrss.org ?
I installed from CPanel and don't want to go messing with the files directly on the server.
Thanks

**Comment by marienfressinaud** [comment]
I'll do but I saw a lot of issues related to 1.22 and I was wondering if @Alkarex wanted to release a version 1.22.1 soon? In this case it would be better to wait a bit.

Note: as always we don't enable the web update immediately so we have time to detect potential issues first.

**Comment by Alkarex** [comment]
Indeed, I was about to answer something similar 🤓

**Comment by howiefc** [comment]
Thanks to both of you for the response, looks like waiting will be better for me.

**Comment by marienfressinaud** [comment]
@howiefc If you didn't notice, you can update FreshRSS 1.22.1 now!
