### ISSUE TITLE
Adding 1.22.0 version

### ISSUE THREAD

**Issue by vonguyenkhang** [FreshRSS/update.freshrss.org#7]
Hi, FreshRSS 1.22.0 was released 3 days ago but the update server was not updated yet (still 1.21.0).

**Comment by Alkarex** [comment]
Coming soon!
https://github.com/FreshRSS/update.freshrss.org/issues/6#issuecomment-1778617404
https://github.com/FreshRSS/FreshRSS/discussions/5751

**Comment by vonguyenkhang** [comment]
Sorry I didn't notice.

**Comment by marienfressinaud** [comment]
@vonguyenkhang If you didn't notice, you can update FreshRSS 1.22.1 now!

**Comment by vonguyenkhang** [comment]
> @vonguyenkhang If you didn't notice, you can update FreshRSS 1.22.1 now!

I've already updated to 1.22.1 successfully, thanks.
